#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.
nums=1

while [ $nums -le 100 ]; do
    if [ $((nums % 3)) -eq 0 ] && [ $((nums % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((nums % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((nums % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$nums"
    fi
    (( nums++ ))
done
