#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
while IFS=':' read -r username _ user_id _ directory_path _; do
	echo "$username"
	echo "$user_id"
	echo "$directory_path"
done < /etc/passwd
