#!/usr/bin/env bash
#uses a while loop to iterate from 1 to 20. Inside the loop, it uses a case statement to check the value of the variable num
num=1
while [ $num -le 20 ]
do
	case $num in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo $num
			;;
	esac
	(( num++ ))
done
